name: vpn_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_frame: 
    git:
      url: https://github.com/sanihaq/flutter_web_frame.git
  collection: ^1.17.1
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  gradient_borders: ^1.0.0
  flutter_reactive_value: ^1.0.4
  window_manager: ^0.3.5
  flutter_persistent_value_notifier: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AppIcons
      fonts:
       - asset: assets/fonts/AppIcons.ttf
    - family: Antonio
      fonts:
      - asset: assets/fonts/Antonio/static/Antonio-Light.ttf
        weight: 300
    - family: Poppins
      fonts:
      - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        weight: 600

