name: Web Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: "Web Build 🔧"
        run: |
          flutter pub get
          flutter build web --release --base-href /${{ github.event.repository.name }}/
      - name: "Web Deploy 🚀"
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: build/web